print("\"Khal Drogo's favorite word is \"athjahakar\"\"")
print("Did Joffrey agree? \nHe did. He also said \"I love using \\n\"")
print('-Did Joffrey agree? \n -He did. He also said "I love using \\n".')
print("Winter " + "came" + " for" + " the" +  " House " + "of" + " Frey")
print("Winter" + " " + "came" + " " + "for" + " " + "the" + " " + "House" + " " + "of" + " " + "Frey")
print(chr(43))