s = ",,,Привет, меня зовут Дима, я из Минска"
print(s.find("в"))
print(s.index("и"))
print(s.replace("При", "123"))
print(s.split(","))
print(s)
print(type(s))
print(s.isdigit())
print(s.isalpha())
print(s.startswith(" Привет"))
print(s.count("е"))
print(s.lstrip(","))
print(s.zfill(45))
print("Hello {1} {0}".format("Zadvorny" ,"Dima"))
print("Привет {0}  {1}  {2}".format("Задворный" ,"Дмитрий", "Михайлович"))
print("{3} , {5} , {7}".format(*"123456789"))